/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum__locales = pgEnum('enum__locales', ['en', 'ar'])
export const enum_users_role = pgEnum('enum_users_role', ['admin', 'editor'])
export const enum_app_users_selected_language = pgEnum('enum_app_users_selected_language', [
  'en',
  'ar',
  'fa',
])
export const enum_app_users_selected_theme = pgEnum('enum_app_users_selected_theme', [
  'light',
  'dark',
  'system',
])
export const enum_messages_role = pgEnum('enum_messages_role', ['user', 'assistant', 'system'])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    role: enum_users_role('role').default('editor'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const app_users = pgTable(
  'app_users',
  {
    id: serial('id').primaryKey(),
    supabaseId: varchar('supabase_id').notNull(),
    email: varchar('email'),
    selectedBackground: integer('selected_background_id').references(() => wallpapers.id, {
      onDelete: 'set null',
    }),
    selectedLanguage: enum_app_users_selected_language('selected_language').default('en'),
    selectedTheme: enum_app_users_selected_theme('selected_theme').default('system'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('app_users_supabase_id_idx').on(columns.supabaseId),
    index('app_users_selected_background_idx').on(columns.selectedBackground),
    index('app_users_updated_at_idx').on(columns.updatedAt),
    index('app_users_created_at_idx').on(columns.createdAt),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    prefix: varchar('prefix').default('media'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const wallpaper_categories = pgTable(
  'wallpaper_categories',
  {
    id: serial('id').primaryKey(),
    slug: varchar('slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('wallpaper_categories_updated_at_idx').on(columns.updatedAt),
    index('wallpaper_categories_created_at_idx').on(columns.createdAt),
  ],
)

export const wallpaper_categories_locales = pgTable(
  'wallpaper_categories_locales',
  {
    title: varchar('title').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('wallpaper_categories_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [wallpaper_categories.id],
      name: 'wallpaper_categories_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const wallpapers = pgTable(
  'wallpapers',
  {
    id: serial('id').primaryKey(),
    file: integer('file_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    category: integer('category_id')
      .notNull()
      .references(() => wallpaper_categories.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('wallpapers_file_idx').on(columns.file),
    index('wallpapers_category_idx').on(columns.category),
    index('wallpapers_updated_at_idx').on(columns.updatedAt),
    index('wallpapers_created_at_idx').on(columns.createdAt),
  ],
)

export const wallpapers_locales = pgTable(
  'wallpapers_locales',
  {
    title: varchar('title').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('wallpapers_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [wallpapers.id],
      name: 'wallpapers_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const cities = pgTable(
  'cities',
  {
    id: serial('id').primaryKey(),
    latitude: numeric('latitude', { mode: 'number' }).notNull(),
    longitude: numeric('longitude', { mode: 'number' }).notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('cities_updated_at_idx').on(columns.updatedAt),
    index('cities_created_at_idx').on(columns.createdAt),
  ],
)

export const cities_locales = pgTable(
  'cities_locales',
  {
    name: varchar('name').notNull(),
    country: varchar('country').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('cities_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [cities.id],
      name: 'cities_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const calendar_events = pgTable(
  'calendar_events',
  {
    id: serial('id').primaryKey(),
    date: timestamp('date', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('calendar_events_updated_at_idx').on(columns.updatedAt),
    index('calendar_events_created_at_idx').on(columns.createdAt),
  ],
)

export const calendar_events_locales = pgTable(
  'calendar_events_locales',
  {
    title: varchar('title').notNull(),
    description: varchar('description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('calendar_events_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [calendar_events.id],
      name: 'calendar_events_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const search_suggestions = pgTable(
  'search_suggestions',
  {
    id: serial('id').primaryKey(),
    url: varchar('url').notNull(),
    logo: integer('logo_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('search_suggestions_logo_idx').on(columns.logo),
    index('search_suggestions_updated_at_idx').on(columns.updatedAt),
    index('search_suggestions_created_at_idx').on(columns.createdAt),
  ],
)

export const search_suggestions_locales = pgTable(
  'search_suggestions_locales',
  {
    keyword: varchar('keyword').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('search_suggestions_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [search_suggestions.id],
      name: 'search_suggestions_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const ai_suggestions = pgTable(
  'ai_suggestions',
  {
    id: serial('id').primaryKey(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('ai_suggestions_updated_at_idx').on(columns.updatedAt),
    index('ai_suggestions_created_at_idx').on(columns.createdAt),
  ],
)

export const ai_suggestions_locales = pgTable(
  'ai_suggestions_locales',
  {
    prompt: varchar('prompt').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('ai_suggestions_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [ai_suggestions.id],
      name: 'ai_suggestions_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const timezones = pgTable(
  'timezones',
  {
    id: serial('id').primaryKey(),
    label: varchar('label').notNull(),
    offset: varchar('offset').notNull(),
    timezoneId: varchar('timezone_id').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('timezones_updated_at_idx').on(columns.updatedAt),
    index('timezones_created_at_idx').on(columns.createdAt),
  ],
)

export const conversations = pgTable(
  'conversations',
  {
    id: serial('id').primaryKey(),
    appUser: integer('app_user_id')
      .notNull()
      .references(() => app_users.id, {
        onDelete: 'set null',
      }),
    title: varchar('title').default('New Chat'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('conversations_app_user_idx').on(columns.appUser),
    index('conversations_updated_at_idx').on(columns.updatedAt),
    index('conversations_created_at_idx').on(columns.createdAt),
  ],
)

export const messages = pgTable(
  'messages',
  {
    id: serial('id').primaryKey(),
    conversation: integer('conversation_id')
      .notNull()
      .references(() => conversations.id, {
        onDelete: 'set null',
      }),
    role: enum_messages_role('role').notNull(),
    content: varchar('content').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('messages_conversation_idx').on(columns.conversation),
    index('messages_updated_at_idx').on(columns.updatedAt),
    index('messages_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    'app-usersID': integer('app_users_id'),
    mediaID: integer('media_id'),
    'wallpaper-categoriesID': integer('wallpaper_categories_id'),
    wallpapersID: integer('wallpapers_id'),
    citiesID: integer('cities_id'),
    'calendar-eventsID': integer('calendar_events_id'),
    'search-suggestionsID': integer('search_suggestions_id'),
    'ai-suggestionsID': integer('ai_suggestions_id'),
    timezonesID: integer('timezones_id'),
    conversationsID: integer('conversations_id'),
    messagesID: integer('messages_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_app_users_id_idx').on(columns['app-usersID']),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_wallpaper_categories_id_idx').on(
      columns['wallpaper-categoriesID'],
    ),
    index('payload_locked_documents_rels_wallpapers_id_idx').on(columns.wallpapersID),
    index('payload_locked_documents_rels_cities_id_idx').on(columns.citiesID),
    index('payload_locked_documents_rels_calendar_events_id_idx').on(columns['calendar-eventsID']),
    index('payload_locked_documents_rels_search_suggestions_id_idx').on(
      columns['search-suggestionsID'],
    ),
    index('payload_locked_documents_rels_ai_suggestions_id_idx').on(columns['ai-suggestionsID']),
    index('payload_locked_documents_rels_timezones_id_idx').on(columns.timezonesID),
    index('payload_locked_documents_rels_conversations_id_idx').on(columns.conversationsID),
    index('payload_locked_documents_rels_messages_id_idx').on(columns.messagesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['app-usersID']],
      foreignColumns: [app_users.id],
      name: 'payload_locked_documents_rels_app_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['wallpaper-categoriesID']],
      foreignColumns: [wallpaper_categories.id],
      name: 'payload_locked_documents_rels_wallpaper_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['wallpapersID']],
      foreignColumns: [wallpapers.id],
      name: 'payload_locked_documents_rels_wallpapers_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['citiesID']],
      foreignColumns: [cities.id],
      name: 'payload_locked_documents_rels_cities_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['calendar-eventsID']],
      foreignColumns: [calendar_events.id],
      name: 'payload_locked_documents_rels_calendar_events_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['search-suggestionsID']],
      foreignColumns: [search_suggestions.id],
      name: 'payload_locked_documents_rels_search_suggestions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['ai-suggestionsID']],
      foreignColumns: [ai_suggestions.id],
      name: 'payload_locked_documents_rels_ai_suggestions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['timezonesID']],
      foreignColumns: [timezones.id],
      name: 'payload_locked_documents_rels_timezones_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['conversationsID']],
      foreignColumns: [conversations.id],
      name: 'payload_locked_documents_rels_conversations_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['messagesID']],
      foreignColumns: [messages.id],
      name: 'payload_locked_documents_rels_messages_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_app_users = relations(app_users, ({ one }) => ({
  selectedBackground: one(wallpapers, {
    fields: [app_users.selectedBackground],
    references: [wallpapers.id],
    relationName: 'selectedBackground',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_wallpaper_categories_locales = relations(
  wallpaper_categories_locales,
  ({ one }) => ({
    _parentID: one(wallpaper_categories, {
      fields: [wallpaper_categories_locales._parentID],
      references: [wallpaper_categories.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_wallpaper_categories = relations(wallpaper_categories, ({ many }) => ({
  _locales: many(wallpaper_categories_locales, {
    relationName: '_locales',
  }),
}))
export const relations_wallpapers_locales = relations(wallpapers_locales, ({ one }) => ({
  _parentID: one(wallpapers, {
    fields: [wallpapers_locales._parentID],
    references: [wallpapers.id],
    relationName: '_locales',
  }),
}))
export const relations_wallpapers = relations(wallpapers, ({ one, many }) => ({
  file: one(media, {
    fields: [wallpapers.file],
    references: [media.id],
    relationName: 'file',
  }),
  category: one(wallpaper_categories, {
    fields: [wallpapers.category],
    references: [wallpaper_categories.id],
    relationName: 'category',
  }),
  _locales: many(wallpapers_locales, {
    relationName: '_locales',
  }),
}))
export const relations_cities_locales = relations(cities_locales, ({ one }) => ({
  _parentID: one(cities, {
    fields: [cities_locales._parentID],
    references: [cities.id],
    relationName: '_locales',
  }),
}))
export const relations_cities = relations(cities, ({ many }) => ({
  _locales: many(cities_locales, {
    relationName: '_locales',
  }),
}))
export const relations_calendar_events_locales = relations(calendar_events_locales, ({ one }) => ({
  _parentID: one(calendar_events, {
    fields: [calendar_events_locales._parentID],
    references: [calendar_events.id],
    relationName: '_locales',
  }),
}))
export const relations_calendar_events = relations(calendar_events, ({ many }) => ({
  _locales: many(calendar_events_locales, {
    relationName: '_locales',
  }),
}))
export const relations_search_suggestions_locales = relations(
  search_suggestions_locales,
  ({ one }) => ({
    _parentID: one(search_suggestions, {
      fields: [search_suggestions_locales._parentID],
      references: [search_suggestions.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_search_suggestions = relations(search_suggestions, ({ one, many }) => ({
  logo: one(media, {
    fields: [search_suggestions.logo],
    references: [media.id],
    relationName: 'logo',
  }),
  _locales: many(search_suggestions_locales, {
    relationName: '_locales',
  }),
}))
export const relations_ai_suggestions_locales = relations(ai_suggestions_locales, ({ one }) => ({
  _parentID: one(ai_suggestions, {
    fields: [ai_suggestions_locales._parentID],
    references: [ai_suggestions.id],
    relationName: '_locales',
  }),
}))
export const relations_ai_suggestions = relations(ai_suggestions, ({ many }) => ({
  _locales: many(ai_suggestions_locales, {
    relationName: '_locales',
  }),
}))
export const relations_timezones = relations(timezones, () => ({}))
export const relations_conversations = relations(conversations, ({ one }) => ({
  appUser: one(app_users, {
    fields: [conversations.appUser],
    references: [app_users.id],
    relationName: 'appUser',
  }),
}))
export const relations_messages = relations(messages, ({ one }) => ({
  conversation: one(conversations, {
    fields: [messages.conversation],
    references: [conversations.id],
    relationName: 'conversation',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    'app-usersID': one(app_users, {
      fields: [payload_locked_documents_rels['app-usersID']],
      references: [app_users.id],
      relationName: 'app-users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    'wallpaper-categoriesID': one(wallpaper_categories, {
      fields: [payload_locked_documents_rels['wallpaper-categoriesID']],
      references: [wallpaper_categories.id],
      relationName: 'wallpaper-categories',
    }),
    wallpapersID: one(wallpapers, {
      fields: [payload_locked_documents_rels.wallpapersID],
      references: [wallpapers.id],
      relationName: 'wallpapers',
    }),
    citiesID: one(cities, {
      fields: [payload_locked_documents_rels.citiesID],
      references: [cities.id],
      relationName: 'cities',
    }),
    'calendar-eventsID': one(calendar_events, {
      fields: [payload_locked_documents_rels['calendar-eventsID']],
      references: [calendar_events.id],
      relationName: 'calendar-events',
    }),
    'search-suggestionsID': one(search_suggestions, {
      fields: [payload_locked_documents_rels['search-suggestionsID']],
      references: [search_suggestions.id],
      relationName: 'search-suggestions',
    }),
    'ai-suggestionsID': one(ai_suggestions, {
      fields: [payload_locked_documents_rels['ai-suggestionsID']],
      references: [ai_suggestions.id],
      relationName: 'ai-suggestions',
    }),
    timezonesID: one(timezones, {
      fields: [payload_locked_documents_rels.timezonesID],
      references: [timezones.id],
      relationName: 'timezones',
    }),
    conversationsID: one(conversations, {
      fields: [payload_locked_documents_rels.conversationsID],
      references: [conversations.id],
      relationName: 'conversations',
    }),
    messagesID: one(messages, {
      fields: [payload_locked_documents_rels.messagesID],
      references: [messages.id],
      relationName: 'messages',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum__locales: typeof enum__locales
  enum_users_role: typeof enum_users_role
  enum_app_users_selected_language: typeof enum_app_users_selected_language
  enum_app_users_selected_theme: typeof enum_app_users_selected_theme
  enum_messages_role: typeof enum_messages_role
  users_sessions: typeof users_sessions
  users: typeof users
  app_users: typeof app_users
  media: typeof media
  wallpaper_categories: typeof wallpaper_categories
  wallpaper_categories_locales: typeof wallpaper_categories_locales
  wallpapers: typeof wallpapers
  wallpapers_locales: typeof wallpapers_locales
  cities: typeof cities
  cities_locales: typeof cities_locales
  calendar_events: typeof calendar_events
  calendar_events_locales: typeof calendar_events_locales
  search_suggestions: typeof search_suggestions
  search_suggestions_locales: typeof search_suggestions_locales
  ai_suggestions: typeof ai_suggestions
  ai_suggestions_locales: typeof ai_suggestions_locales
  timezones: typeof timezones
  conversations: typeof conversations
  messages: typeof messages
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_app_users: typeof relations_app_users
  relations_media: typeof relations_media
  relations_wallpaper_categories_locales: typeof relations_wallpaper_categories_locales
  relations_wallpaper_categories: typeof relations_wallpaper_categories
  relations_wallpapers_locales: typeof relations_wallpapers_locales
  relations_wallpapers: typeof relations_wallpapers
  relations_cities_locales: typeof relations_cities_locales
  relations_cities: typeof relations_cities
  relations_calendar_events_locales: typeof relations_calendar_events_locales
  relations_calendar_events: typeof relations_calendar_events
  relations_search_suggestions_locales: typeof relations_search_suggestions_locales
  relations_search_suggestions: typeof relations_search_suggestions
  relations_ai_suggestions_locales: typeof relations_ai_suggestions_locales
  relations_ai_suggestions: typeof relations_ai_suggestions
  relations_timezones: typeof relations_timezones
  relations_conversations: typeof relations_conversations
  relations_messages: typeof relations_messages
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
